package pipi.mod.unltd_furnace;

import net.minecraftforge.fml.common.ModMetadata;

public class ModInfo {
	public static final String MODID = "unltd_furnace";
	public static final String NAME = "Unlimited Furnace";
	public static final String VERSION = "1.0.0";
	
	public static final String URL = "https://www.curseforge.com/minecraft/mc-mods/unlimited-furnace";
	public static final String UPDATE_JSON = "https://raw.githubusercontent.com/pizza-pan88/Unlimited-Furnace/resource/update.json";
	
	public static void loadInfo(ModMetadata meta) {
		meta.modId = MODID;
		meta.version = VERSION;
		meta.name = NAME;
		meta.description = "The goal is to bake...";
		meta.url = URL;
		meta.logoFile = "logo.png";
		meta.authorList.add("Pizza_pan88");
		meta.updateJSON = UPDATE_JSON;
		meta.autogenerated = false;
	}
	
}
